name: Publish Release to GitHub Packages

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    timeout-minutes: 3

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Set up Java
        uses: actions/setup-java@1bcf9fb12cf4aa7d266a90ae39939e61372fe520 # v5.4.0
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@3f131e8634966bd73d06cc69884922b02e6faf92 # v6.2.0
        with:
          cache-read-only: false

      - name: Extract version from release tag
        id: get_version
        env:
          TAG_NAME: ${{ github.event.release.tag_name }}
        run: |
          echo "Release tag: $TAG_NAME"
          # Use shell parameter expansion to remove a leading 'v' if it exists.
          VERSION_WITHOUT_V="${TAG_NAME#v}"
          echo "version=${VERSION_WITHOUT_V}" >> "$GITHUB_OUTPUT"

      - name: Build and Publish with Gradle
        run: ./gradlew clean build publishMavenPublicationToGithubPackages -Pversion="$VERSION"
        env:
          VERSION: ${{ steps.get_version.outputs.version }}
          GPR_USER: ${{ github.actor }}
          GPR_TOKEN: ${{ secrets.GITHUB_TOKEN }}
