name: Publish Release to GitHub Packages

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    timeout-minutes: 3

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Set up Java
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5.2.0
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@50e97c2cd7a37755bbfafc9c5b7cafaece252f6e # v6.1.0
        with:
          cache-read-only: false

      - name: Extract version from release tag
        id: get_version
        env:
          TAG_NAME: ${{ github.event.release.tag_name }}
        run: |
          echo "Release tag: $TAG_NAME"
          # Use shell parameter expansion to remove a leading 'v' if it exists.
          VERSION_WITHOUT_V="${TAG_NAME#v}"
          echo "version=${VERSION_WITHOUT_V}" >> "$GITHUB_OUTPUT"

      - name: Build and Publish with Gradle
        run: ./gradlew clean build publishMavenPublicationToGithubPackages -Pversion="$VERSION"
        env:
          VERSION: ${{ steps.get_version.outputs.version }}
          GPR_USER: ${{ github.actor }}
          GPR_TOKEN: ${{ secrets.GITHUB_TOKEN }}
